# Exploratory Data Analysis part 1 Studio

## Data Analysis of IMDB movies data

#### The studio will continue working through the ["A Comprehensive Guide To Data Analysis using Pandas: Hands-On Data Analysis on IMDB movies data"](https://www.analyticsvidhya.com/blog/2021/05/a-comprehensive-guide-to-data-analysis-using-pandas-hands-on-data-analysis-on-imdb-movies-data/) in the **Data Analysis of IMDB movies data** section

#### Blocks have been created for your code

#### Follow the link in the article to download the dataset from [Kaggle](https://www.kaggle.com/PromptCloudHQ/imdb-data).  Link contained within the article.

### 1. Read data

In [8]:
# import pandas
import pandas as pd 

# create your data variabe using .read_csv 
movie_df = pd.read_csv ('IMDB-Movie-Data.csv')
# create your data_indexed varialbe here
movie_df = pd.read_csv ('IMDB-Movie-Data.csv' , index_col = ['Title'])
movie_df

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [ ]:
# If you are having trouble reading your file, try finding the path.  
    # Right click on your data set, on the pop-up menu select "Copy Path" then paste it into your read_csv() function.

In [ ]:
# Read data with specified explicit index



#print(data_indexed)

### 2. View Data
#### As we go through this section, write your own definitions of what each function does as a comment in the code box.

In [ ]:
# Use the head() function to view the first 5 rows of the data set

In [ ]:
# Use the tail() function to view the last 5 rows of the data set

### 3. Understand basic information about the data
#### As we go through this section, write your own definitions of what each function does as a comment in the code box.

In [ ]:
# The info() function:

In [ ]:
# shape:


# what information does shape provide?  what is the order?

In [ ]:
# columns:


# what information does columns provide?

In [ ]:
# The describe() function:

### 4. Data Selection -- Indexing and Slicing

In [ ]:
#  Extract data as series
# define and print the variable 'genre'

In [ ]:
# Extract the data as a dataframe and print it

In [ ]:
# Extract data using rows

# loc function

In [ ]:
# iloc function

### 5. Data Selection - Based on Conditional Filtering

In [ ]:
# Use the code block to select movies that have been release between 2010-2016, with a rating of less than 6.0, but generated a signifianct (top) revenue.

In [117]:
# Note: The article is expecting more than 1 Twilight movie at the time of publishing.  
#To find the second Twilight movie, try manipulating the quantile value.  
#How specific can you get?